# Generated by Django 5.2.4 on 2025-07-05 13:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_scraperschedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scraperschedule',
            name='run_time',
            field=models.TimeField(default=datetime.time(0, 0), help_text='Time of day to run the task'),
        ),
    ]
