# Generated by Django 5.2.4 on 2025-07-05 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_scraperschedule_run_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapeditem',
            name='image_file',
            field=models.ImageField(blank=True, null=True, upload_to='scraped_images/'),
        ),
    ]
